### ISSUE TITLE
Bug trying to remove master_frames

### ISSUE THREAD

**Issue by martinberoiz** [toros-astro/imageredux#22]
I run imageredux 

    $ python imageredux.py -i O2_short/Jan04/20170113/ -o ~/Desktop/out/

and it gives me this error.

```
<STATUS> Starting image redux
Traceback (most recent call last):
  File "imageredux.py", line 258, in <module>
    main()
  File "imageredux.py", line 199, in main
    master_dark = do_dark_combine(dark_list, master_frame_dir)
  File "imageredux.py", line 43, in do_dark_combine
    master_dark = ccdproc.combine(dark_list, method="median", unit="u.adu", clobber=True)
  File "/Users/cgwa/.virtualenvs/redux/lib/python3.6/site-packages/ccdproc/combiner.py", line 579, in combine
    if isinstance(img_list[0], CCDData):
IndexError: list index out of range
```

The reason is that in line 201, it's trying to remove "master_frames" from a list that does not contain any "master_frames" string in it. 

    obj_dirs.remove("master_frames")

**Comment by martinberoiz** [comment]
7fff5017f08275e162cef7e37042d48dd41d5dae closed this
