### ISSUE TITLE
tests not passing

### ISSUE THREAD

**Issue by martinberoiz** [toros-astro/imageredux#8]
Hey guys, 

The tests are not passing and it's actually the same error for both of them.

After the function (either doDarkComb or redux) is done, it should return the name of the file(s) it created so that the calling party can retrieve that file name and continue the process.

Right now it seems that @juanlg7's is returning a CCDData object and @moemyself3's returns `None`

```
$ python tests/test_imageredux.py -v
test_doDarkComb (__main__.TestDarkComb) ... ERROR
ERROR
test_redux (__main__.TestRedux) ... image.fits
dark_master.fits
flat_master.fits
ERROR
======================================================================
ERROR: test_doDarkComb (__main__.TestDarkComb)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_imageredux.py", line 29, in test_doDarkComb
    self.assertTrue(os.path.exists(self.darkmaster_fname))
  File "/home/travis/virtualenv/python3.6.2/lib/python3.6/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not CCDData
======================================================================
ERROR: test_doDarkComb (__main__.TestDarkComb)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_imageredux.py", line 25, in tearDown
    os.remove(self.darkmaster_fname)
TypeError: remove: path should be string, bytes or os.PathLike, not CCDData
======================================================================
ERROR: test_redux (__main__.TestRedux)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_imageredux.py", line 61, in test_redux
    self.assertTrue(os.path.exists(self.redux_name))
  File "/home/travis/virtualenv/python3.6.2/lib/python3.6/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
----------------------------------------------------------------------
Ran 2 tests in 0.062s
FAILED (errors=3)
```

**Comment by moemyself3** [comment]
redux passes test!!

as of last commit:
 [https://github.com/toros-astro/imageredux/commit/d6d0419f7de8eb448aa63cf4a4d35aa38c0b2681](url)

**Comment by moemyself3** [comment]
@juanlg7 The error is specific to the return type. 
If you take a look at the changes I made, you'll see I created a variable to store the name of the file as a string rather than return the variable you are using to store the data.

**Comment by martinberoiz** [comment]
Great job 👍

**Comment by moemyself3** [comment]
The tests in this issue are obsolete. We did figure out the specific correction needed that was addressed by the issue, but still need to conform to the string return type on some functions before closing this issue.

**Comment by moemyself3** [comment]
Currently the datatype being passed on all functions are CCDData type. 
The code successfully executes.
